### ISSUE TITLE
toSatisfyOnFlush does not work with delays?

### ISSUE THREAD

**Issue by schmkr** [just-jeb/jest-marbles#394]
Hi,

Today I learned about this new helper function `toSatisfyOnFlush` which removes the need to run tests in a testScheduler.run() callback, manually flushing an observable after subscribing.

While replacing those testScheduler.run() tests with `expect(stream).toSatisfyOnFlush(() => {})`, I came across a use case where the use of the `delay()` operator does not seem to get flushed with that helper function.

Stream:

```ts
// NgRx Effect:
readonly pongReceived$ = createEffect(
  () =>
    this.actions$.pipe(
      ofType(actions.pongReceived),
      delay(60000), // one minute
      tap(() => this.someService.sendPing()),
    ),
  { dispatch: false },
);
```

With TestScheduler.run, this works and the spied method has been called

```ts
it('should call someService.sendPing', () => {
  testScheduler.run(({ hot, flush }) => {
    const action = actions.pongReceived();
    actions$ = hot('-a', { a: action });
    const spy = jest
      .spyOn(someService, 'sendPing')
      .mockImplementationOnce(() => undefined);

    effects.pongReceived$.subscribe();
    flush();

    expect(spy).toHaveBeenCalledTimes(1);
  });
});
```

With `toSatisfyOnFlush` this does not seem to work:

```ts
it('should call someService.sendPing', () => {
  testScheduler.run(({ hot, flush }) => {
    const action = actions.pongMessageReceived();
    actions$ = hot('-a', { a: action });
    const spy = jest
      .spyOn(someService, 'sendPing')
      .mockImplementationOnce(() => undefined);

  expect(effects.pongReceived$).toSatisfyOnFlush(() => {
    expect(spy).toHaveBeenCalledTimes(1);
  });
});
```

Is there a particular reason, time related operators aren't flushed? Based on the name of the helper function, I would have assumed it would. Is it related to the time progression syntax not being supported (#117)

**Comment by MillerSvt** [comment]
It seems to be fixed in 3.1.0
