### ISSUE TITLE
RangeError: Invalid count value at String.repeat (<anonymous>), When attempt to emit null values

### ISSUE THREAD

**Issue by dance-cmdr** [just-jeb/jest-marbles#79]
## Background

I'm trying to test a few observable initialised with a null value. The use case is usually for testing an element that is used with CombineWithLatest but we still want to allow the main observable emit before the second component receives its first value.

```
a$.pipe(
   combineWithLatest(b$.pipe(startWith(null)))
)
```

Which would roughly resolve in

```
n = null

a$     ----a   ----a   ----a  --|
b$     n----   -----   b----  --|
ab$    ---(an)----(an)----(ab)--|
```

This is a valid case, however, marbilizer throws a RangeError in all the test cases mentioned bellow.

<img width="894" alt="screenshot 2018-12-06 at 12 10 59" src="https://user-images.githubusercontent.com/1997886/49583413-0fa56e80-f950-11e8-8316-3c921374d8f9.png">

Error Log Trace
````
 RangeError: Invalid count value
        at String.repeat (<anonymous>)

      at Function../index.ts.Marblizer.marblize (node_modules/jest-marbles/umd/webpack:/JestMarbles/src/marblizer.ts:14:56)
      at Object.toBeNotifications (node_modules/jest-marbles/umd/webpack:/JestMarbles/src/jest/custom-matchers.ts:24:32)
      at Object.throwingMatcher [as toBeNotifications] (node_modules/expect/build/index.js:320:33)
      at TestScheduler.assertDeepEqual (node_modules/jest-marbles/umd/webpack:/JestMarbles/src/rxjs/assert-deep-equal.ts:29:20)
      at Object.<anonymous> (node_modules/jest-marbles/umd/webpack:/JestMarbles/index.ts:65:19)
````

## Tests Cases
````
test('it should merge two observable start with null', () => {
        const e1 = hot('----a--^--b-------c--|');
        const e2 = hot('---d-^--e---------f-----|');
        const expected = cold('n--(be)----c-f-----|', {n: null});

        const c$ = e1.pipe(
            merge(e2),
            startWith(null)
        );

        expect(c$).toBeObservable(expected);
});

test('it should merge two observables start with false', () => {
    const e1 = hot('----a--^--b-------c--|');
    const e2 = hot('---d-^--e---------f-----|');
    const expected = cold('n--(be)----c-f-----|', {n: false});

    const c$ = e1.pipe(
        merge(e2),
        startWith(false)
    );

    expect(c$).toBeObservable(expected);
});


test('it start with false', () => {
    const e1 = cold('--a--|');
    const expected = cold('f--a--|', {f:false});

    const c$ = e1.pipe(
        startWith(false)
    );

    expect(c$).toBeObservable(expected);
});
````

I checked the changelog and it appears that in 2.1.0 you support primitive values, so, 
If you can confirm that I'm not doing something stupid I'll try to make some time to fix it.

**Comment by meltedspark** [comment]
Seems like a valid case to me (except for the second test where you specify `n: false` although there is no `n` in the marble, but that I believe is just a typo).   
I'm not quite sure why it doesn't work, since as you mentioned all non-character values (including primitives) are supported in `2.1.0`.  
[Here](https://github.com/meltedspark/jest-marbles/issues/75) is a related issue that looks pretty much similar to yours. You're more than welcome to investigate and try to fix, the contribution is very much appreciated. 
But first make sure you're indeed with the latest version of the library.

**Comment by dance-cmdr** [comment]
Hi @meltedspark!
Thanks for coming back to me so fast.

Yes, you are correct, there was a typo in the second case (corrected now).

I'm confident I'm using 2.1.0. The latest the moment I'm writing this comment.

```
//yarn.lock registry
jest-marbles@^2.1.0:
  version "2.1.0"
  resolved "https://registry.npmjs.org/jest-marbles/-/jest-marbles-2.1.0.tgz#4714e5a611a8fa3cf32898a1a8edb327e42111e9"
```

I'll try to make some time for fixing it. I'll comment here when I'll actively pick it up. Meanwhile if someone else is faster than me on that, feel free to grab it.
